#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if 
	test $(grep 'tryMe' README.md |wc -l) = 0
then
	cat <<\EOF
README.md needs to have tryMe to allow the commit to work
EOF
	exit 1
fi
